apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::327796148680:role/app-eks-node-group
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-08T20:55:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "35361"
  uid: 0f512c1c-efad-4f6c-9e96-0816047cc568
